spring.application.name=autostock-backend

# Profil actif par défaut = dev ; Render surchargera cette variable
# d'environnement pour activer le profil prod.
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
